version: "2.1"

volumes:
  settings:
  cache:

services:
  menu-app:
    build: ./
    privileged: true
    network_mode: host
    ports:
      - '8080'
    volumes:
      - 'cache:/cache'
    labels:
      io.balena.features.supervisor-api: '1'
      # io.balena.features.dbus: '1'
    # environment:
    #   DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    
  browser:
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true
    network_mode: host
    ports:
        - '5011' # management API
        - '35173' # Chromium debugging port
    volumes:
      - 'settings:/data'
