version: "2.1"

volumes:
  settings:

services:
  menu-app:
    build: ./
    privileged: true
    network_mode: host
    ports:
      - '8080'
  browser:
    image: bh.cr/balenalabs/browser-amd64
    privileged: true
    network_mode: host
    ports:
        - '5011' # management API
        - '35173' # Chromium debugging port
    volumes:
      - 'settings:/data'
